Make auditd job more resilient
We've seen cases where auditd doesn't reliably start when there are many
audit rules (`ENOBUFS`). This commit attempts to address that by looping
for five minutes before giving up.

Intended to fix:
```
1 of 12 pre-start scripts failed. Failed Jobs: auditd
```

Fixes, from /var/log/daemon.log:
```
auditd[6522]: Error receiving audit netlink packet (No buffer space available)
```

Signed-off-by: Brian Cunnie <bcunnie@vmware.com>
Signed-off-by: Daniel Lynch <lynchda@vmware.com>

diff --git a/jobs/auditd/templates/pre-start b/jobs/auditd/templates/pre-start
--- a/jobs/auditd/templates/pre-start
+++ b/jobs/auditd/templates/pre-start
@@ -19,5 +19,17 @@ if ! grep -e '^-e 2$' /etc/audit/rules.d/audit.rules -q; then
 # Make audit rules immutable; added by auditd job (os-conf-release)
 -e 2' >> /etc/audit/rules.d/audit.rules
 
-  service auditd restart
+  # If auditd has trouble coming up, (e.g. `ENOBUFS`), we try for 5 minutes
+  # before giving up
+  COUNT=0
+  service auditd stop
+  while ! service auditd status && [ $COUNT -lt 10 ]; do
+    service auditd restart
+    COUNT=$(( COUNT + 1 ))
+    sleep 30
+  done
+  if [ $COUNT -ge 10 ]; then
+    echo "Could not start auditd; tried $COUNT times. Check auditd logs"
+    exit 1
+  fi
 fi
